#! /bin/sh -ex
#
# Updates the infrastructure and packages for supported OSes

SCRIPT_URL=git://github.com/rock-core/rock_ci

if ! test -d "$ROCK_CI_SCRIPT_DIR"; then
    git clone "$SCRIPT_URL" "$ROCK_CI_SCRIPT_DIR"
else
    cd "$ROCK_CI_SCRIPT_DIR"
    git remote update
    git reset --hard origin/master
fi

if which apt-get 2>&1; then
    sudo apt-get update
    sudo apt-get -y install wget ruby doxygen ruby1.9.1-dev
    sudo apt-get -y upgrade
fi

