#! /bin/sh -ex
#
# Updates the infrastructure and packages for supported OSes

SCRIPT_URL=git://github.com/rock-core/rock_ci
CONFIG_URL=git://github.com/rock-core/rock_ci_conf

if ! test -d "$SCRIPT_DIR"; then
    git clone "$SCRIPT_URL" "$SCRIPT_DIR"
else
    cd "$SCRIPT_DIR"
    git remote update
    git reset --hard origin/master
fi

if test -z "$CONFIG_DIR"; then
    if ! test -d "$CONFIG_DIR"; then
        git clone "$CONFIG_URL" "$CONFIG_DIR"
    else
        cd "$CONFIG_DIR"
        git remote update
        git reset --hard origin/master
    fi
fi

if which apt-get 2>&1; then
    sudo apt-get update
    sudo apt-get -y install wget ruby doxygen ruby1.9.1-dev
    sudo apt-get -y upgrade
fi

