#! /bin/sh -ex
#
# Updates the infrastructure and packages for supported OSes

# Install git
if which apt-get 2>&1; then
    if test -n "$ROCK_CI_PACKAGE_CACHE"; then
        mkdir -p "$ROCK_CI_PACKAGE_CACHE"
        sudo rsync -a "$ROCK_CI_PACKAGE_CACHE/" /var/cache/apt/archives/
    fi
    sudo apt-get update
    sudo apt-get -y upgrade
    sudo apt-get -y install git
fi

# Update the script itself
SCRIPT_URL=git://github.com/rock-core/rock_ci
cd "$ROCK_CI_DIR"
cur_id=$(git rev-parse HEAD)
git remote rm origin
git remote add -f origin "$SCRIPT_URL"
git remote update
git reset --hard origin/master
new_id=$(git rev-parse HEAD)
if test "x$cur_id" != "x$new_id"; then
    exec "$0" "$@"
fi

if which apt-get 2>&1; then
    sudo apt-get -y install wget ruby1.9.1
    if test -n "$ROCK_CI_PACKAGE_CACHE"; then
        sudo rsync -a /var/cache/apt/archives/ "$ROCK_CI_PACKAGE_CACHE/"
        sudo chown -R ubuntu:ubuntu "$ROCK_CI_PACKAGE_CACHE/"
    fi
fi

