#! /bin/bash
#
# Creates an autobuild cache to speedup bootstraps
#
# All script arguments are passed to the autoproj_bootstrap script
#
# See README.txt for a description of all the environment variables that can be
# used to customize its behaviour.
#
# See README.txt for a description of all the environment variables that can be
# used to customize its behaviour.

echo "$0 started at `date` on `lsb_release -a`"
set -ex

ROCK_CI_DIR=$(dirname $0)
. "$ROCK_CI_DIR/rock-ci-shelllib"

rock_ci_setdefaults

if test -z "$ROCK_CI_AUTOBUILD_CACHE_DIR"; then
    echo "the ROCK_CI_AUTOBUILD_CACHE_DIR environment variable must be set"
    exit 1
fi

if test "x$ROCK_CI_MODE" = "xfull"; then
    rm -rf "$ROCK_CI_AUTOBUILD_CACHE_DIR"
fi

# If there are no autoproj/ directory, we need to start by bootstrapping
rock_ci_setupdev "$@"
echo "Finished preparing, starting build at `date` with $ROCK_CI_RUBY"
rock_ci_autoproj cache $ROCK_CI_AUTOPROJ_OPTIONS "$ROCK_CI_AUTOBUILD_CACHE_DIR"

